services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gql_yoga_playground
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
